# Build Stage
FROM golang:1.24-alpine AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-w -s" -o /app/bin/noject-gateway cmd/gateway/main.go

# Production Stage
FROM alpine:3.20

RUN apk --no-cache add ca-certificates tzdata
WORKDIR /app

COPY --from=builder /app/bin/noject-gateway /app/noject-gateway
COPY configs/ /app/configs/

EXPOSE 8080

ENTRYPOINT ["/app/noject-gateway", "-config", "/app/configs/gateway.yaml"]
